
import { FloodDataPoint } from './types';

export const INITIAL_DATA: FloodDataPoint[] = [
  {
    id: '1',
    locationName: 'Guwahati, Assam (Brahmaputra)',
    latitude: 26.1445,
    longitude: 91.7362,
    rainfall: 480,
    temperature: 29,
    humidity: 88,
    riverDischarge: 15500,
    waterLevel: 14.2,
    elevation: 55,
    landCover: 'Wetland',
    soilType: 'Alluvial',
    populationDensity: 1200,
    infrastructureScore: 4,
    historicalFloods: 18
  },
  {
    id: '2',
    locationName: 'Patna, Bihar (Ganga Basin)',
    latitude: 25.5941,
    longitude: 85.1376,
    rainfall: 310,
    temperature: 31,
    humidity: 78,
    riverDischarge: 19500,
    waterLevel: 11.5,
    elevation: 53,
    landCover: 'Agriculture',
    soilType: 'Silt',
    populationDensity: 1800,
    infrastructureScore: 3,
    historicalFloods: 24
  },
  {
    id: '3',
    locationName: 'Mumbai, MH (Urban Catchment)',
    latitude: 19.0760,
    longitude: 72.8777,
    rainfall: 520,
    temperature: 30,
    humidity: 92,
    riverDischarge: 3200,
    waterLevel: 5.5,
    elevation: 10,
    landCover: 'Urban',
    soilType: 'Loam',
    populationDensity: 21000,
    infrastructureScore: 7,
    historicalFloods: 14
  },
  {
    id: '4',
    locationName: 'Kochi, Kerala (Coastal/Backwater)',
    latitude: 9.9312,
    longitude: 76.2673,
    rainfall: 400,
    temperature: 28,
    humidity: 85,
    riverDischarge: 5200,
    waterLevel: 4.8,
    elevation: 2,
    landCover: 'Wetland',
    soilType: 'Clay',
    populationDensity: 1100,
    infrastructureScore: 6,
    historicalFloods: 10
  },
  {
    id: '5',
    locationName: 'Jodhpur, RJ (Arid/Flash Flood)',
    latitude: 26.2389,
    longitude: 73.0243,
    rainfall: 45,
    temperature: 42,
    humidity: 20,
    riverDischarge: 120,
    waterLevel: 0.8,
    elevation: 231,
    landCover: 'Desert',
    soilType: 'Sandy',
    populationDensity: 450,
    infrastructureScore: 5,
    historicalFloods: 1
  },
  {
    id: '6',
    locationName: 'Kolkata, WB (Hooghly Delta)',
    latitude: 22.5726,
    longitude: 88.3639,
    rainfall: 380,
    temperature: 32,
    humidity: 82,
    riverDischarge: 12000,
    waterLevel: 9.2,
    elevation: 9,
    landCover: 'Urban',
    soilType: 'Clayey Silt',
    populationDensity: 24000,
    infrastructureScore: 6,
    historicalFloods: 16
  },
  {
    id: '7',
    locationName: 'Srinagar, JK (Mountain Riverine)',
    latitude: 34.0837,
    longitude: 74.7973,
    rainfall: 120,
    temperature: 15,
    humidity: 65,
    riverDischarge: 7500,
    waterLevel: 7.8,
    elevation: 1585,
    landCover: 'Forest',
    soilType: 'Rocky',
    populationDensity: 900,
    infrastructureScore: 4,
    historicalFloods: 6
  },
  {
    id: '8',
    locationName: 'Ahmedabad, GJ (Sabarmati)',
    latitude: 23.0225,
    longitude: 72.5714,
    rainfall: 180,
    temperature: 36,
    humidity: 55,
    riverDischarge: 4500,
    waterLevel: 3.2,
    elevation: 53,
    landCover: 'Urban',
    soilType: 'Sandy Loam',
    populationDensity: 9000,
    infrastructureScore: 7,
    historicalFloods: 4
  }
];

export const FEATURE_WEIGHTS = {
  rainfall: 0.30, // Increased as per typical Indian flood datasets
  waterLevel: 0.20,
  riverDischarge: 0.15,
  elevation: -0.15,
  historicalFloods: 0.10,
  populationDensity: 0.05,
  infrastructureScore: -0.05,
  humidity: 0.02
};
