
import { FloodDataPoint, DisasterEvent } from './types';

export const RECENT_DISASTERS: DisasterEvent[] = [
  {
    id: 'disaster-brahmaputra-2026',
    name: 'Brahmaputra Basin Monsoonal Surge',
    country: 'India',
    region: 'Guwahati & Kaziranga, Assam',
    date: 'July 2026',
    category: 'Riverine Overflow',
    latitude: 26.1445,
    longitude: 91.7362,
    rainfall24h: 380,
    peakDischarge: 17200,
    peakWaterLevel: 14.8,
    elevation: 55,
    fatalities: 'Early evacuations executed (>180,000 residents relocated)',
    impactSummary: 'Upper catchment deluge triggered severe riverine cresting above extreme danger levels along the Brahmaputra corridor, testing river embankment defenses.',
    keyDrivers: [
      'Multi-day torrential rain (>380mm/24h) across Himalayan headwaters',
      'High siltation reducing channel volume capacity',
      'Low topographic gradient in alluvial plains'
    ],
    lessonsLearned: [
      'Early telemetry and automated warning sirens minimized casualties',
      'Elevated animal highland corridors prevented wildlife mortality'
    ],
    badgeColor: 'bg-red-600',
    dataPoint: {
      id: 'brahmaputra-2026',
      locationName: 'Guwahati, Assam (Brahmaputra Basin - 2026)',
      latitude: 26.1445,
      longitude: 91.7362,
      rainfall: 380,
      temperature: 28,
      humidity: 89,
      riverDischarge: 17200,
      waterLevel: 14.8,
      elevation: 55,
      landCover: 'Alluvial River Basin',
      soilType: 'Alluvial',
      populationDensity: 1400,
      infrastructureScore: 5,
      historicalFloods: 18,
      isDisasterBenchmark: true,
      disasterEventId: 'disaster-brahmaputra-2026'
    }
  },
  {
    id: 'disaster-konkan-2026',
    name: 'Konkan Coastal Cloudburst & Flash Surge',
    country: 'India',
    region: 'Mumbai & Raigad, Maharashtra',
    date: 'August 2026',
    category: 'Flash Flood',
    latitude: 19.0760,
    longitude: 72.8777,
    rainfall24h: 420,
    peakDischarge: 4800,
    peakWaterLevel: 5.8,
    elevation: 10,
    fatalities: 'Urban inundation, automated stormwater pumps deployed',
    impactSummary: 'High-tide astronomical surge synchronized with 420mm offshore convective rain cells, inundating low-lying urban catchments.',
    keyDrivers: [
      'Coinciding 4.6m astronomical spring high tide locking outfall sluices',
      'Heavy intense convective precipitation bands',
      'High impermeability index in paved urban catchments'
    ],
    lessonsLearned: [
      'Underground holding reservoirs significantly buffered peak flow',
      'Automated sluice gate synchronization based on Doppler radar'
    ],
    badgeColor: 'bg-orange-600',
    dataPoint: {
      id: 'mumbai-2026',
      locationName: 'Mumbai, Maharashtra (Konkan Catchment - 2026)',
      latitude: 19.0760,
      longitude: 72.8777,
      rainfall: 420,
      temperature: 29,
      humidity: 93,
      riverDischarge: 4800,
      waterLevel: 5.8,
      elevation: 10,
      landCover: 'Urban Coastal',
      soilType: 'Loam',
      populationDensity: 21500,
      infrastructureScore: 7,
      historicalFloods: 14,
      isDisasterBenchmark: true,
      disasterEventId: 'disaster-konkan-2026'
    }
  },
  {
    id: 'disaster-wayanad-2024',
    name: 'Wayanad Mountain Torrent & Debris Flow',
    country: 'India',
    region: 'Chooralmala & Mundakkai, Wayanad, Kerala',
    date: 'July 30, 2024',
    category: 'Landslide / Torrent',
    latitude: 11.5540,
    longitude: 76.1344,
    rainfall24h: 572,
    peakDischarge: 7400,
    peakWaterLevel: 6.2,
    elevation: 780,
    fatalities: '400+ casualties',
    impactSummary: 'Continuous 48-hour torrential rain (572mm) saturated the fragile Western Ghats slopes, causing high-velocity debris flows and river torrent surges.',
    keyDrivers: [
      'Over 570mm antecedent rainfall causing 100% soil pore-water liquefaction',
      'Steep slope gradient (>32°) with high velocity boulder runoff',
      'Natural stream narrowing and sudden debris-dam breach'
    ],
    lessonsLearned: [
      'Micro-level slope soil saturation sensors enable hours of advance notice',
      'Night-time evacuation protocols are mandatory during continuous heavy rainfall (>200mm/24h)'
    ],
    badgeColor: 'bg-rose-600',
    dataPoint: {
      id: 'wayanad-2024',
      locationName: 'Wayanad, Kerala (Chooralmala - 2024 Event)',
      latitude: 11.5540,
      longitude: 76.1344,
      rainfall: 572,
      temperature: 22,
      humidity: 98,
      riverDischarge: 7400,
      waterLevel: 6.2,
      elevation: 780,
      landCover: 'Steep Forest / Plantation',
      soilType: 'Rocky Loam',
      populationDensity: 850,
      infrastructureScore: 4,
      historicalFloods: 8,
      isDisasterBenchmark: true,
      disasterEventId: 'disaster-wayanad-2024'
    }
  },
  {
    id: 'disaster-nepal-2024',
    name: 'Bagmati Basin Monsoonal Surge',
    country: 'Nepal',
    region: 'Kathmandu Valley / Bagmati Basin',
    date: 'September 2024',
    category: 'Flash Flood',
    latitude: 27.7172,
    longitude: 85.3240,
    rainfall24h: 342,
    peakDischarge: 16800,
    peakWaterLevel: 6.8,
    elevation: 1350,
    fatalities: 'Severe casualties and infrastructure damage',
    impactSummary: 'Monsoonal depression triggered extreme 24h cloudburst precipitation (342mm) across Kathmandu valley, overtopping river floodwalls.',
    keyDrivers: [
      'Unprecedented 24h cloudburst exceeding 50-year return period',
      'Steep mountain catchment runoff funneling into constricted valley',
      'Floodplain encroachment along river corridors'
    ],
    lessonsLearned: [
      'Upstream Doppler radar and automated cloudburst telemetry are essential',
      'Vertical evacuation corridors required along urban channels'
    ],
    badgeColor: 'bg-red-700',
    dataPoint: {
      id: 'nepal-2024',
      locationName: 'Kathmandu Valley (Bagmati Basin - 2024 Event)',
      latitude: 27.7172,
      longitude: 85.3240,
      rainfall: 342,
      temperature: 19,
      humidity: 94,
      riverDischarge: 16800,
      waterLevel: 6.8,
      elevation: 1350,
      landCover: 'Urban Valley',
      soilType: 'Clayey Silt',
      populationDensity: 19800,
      infrastructureScore: 4,
      historicalFloods: 12,
      isDisasterBenchmark: true,
      disasterEventId: 'disaster-nepal-2024'
    }
  },
  {
    id: 'disaster-sikkim-2023',
    name: 'Teesta River GLOF Surge',
    country: 'India',
    region: 'Chungthang, Sikkim',
    date: 'October 2023',
    category: 'GLOF',
    latitude: 27.5348,
    longitude: 88.6473,
    rainfall24h: 215,
    peakDischarge: 24000,
    peakWaterLevel: 14.5,
    elevation: 1600,
    fatalities: '102 fatalities & extensive infrastructure loss',
    impactSummary: 'Glacial lake moraine failure combined with cloudburst released millions of cubic meters down the Teesta gorge.',
    keyDrivers: [
      'Glacial moraine lake outburst combined with upper basin cloudburst',
      'Confined mountain canyon creating high hydrodynamic waves'
    ],
    lessonsLearned: [
      'Satellite automated GLOF sensors at high-altitude lakes',
      'Spillway designs capable of handling sudden hydrodynamic surges'
    ],
    badgeColor: 'bg-amber-600',
    dataPoint: {
      id: 'sikkim-2023',
      locationName: 'Teesta Basin, Sikkim (Chungthang - 2023 GLOF)',
      latitude: 27.5348,
      longitude: 88.6473,
      rainfall: 215,
      temperature: 14,
      humidity: 90,
      riverDischarge: 24000,
      waterLevel: 14.5,
      elevation: 1600,
      landCover: 'Alpine Gorge',
      soilType: 'Rocky',
      populationDensity: 320,
      infrastructureScore: 3,
      historicalFloods: 5,
      isDisasterBenchmark: true,
      disasterEventId: 'disaster-sikkim-2023'
    }
  },
  {
    id: 'disaster-delhi-2023',
    name: 'Yamuna Floodplain High-Water Event',
    country: 'India',
    region: 'Delhi NCR',
    date: 'July 2023',
    category: 'Riverine Overflow',
    latitude: 28.6692,
    longitude: 77.2315,
    rainfall24h: 153,
    peakDischarge: 26500,
    peakWaterLevel: 20.8,
    elevation: 214,
    fatalities: 'Mass evacuation (>26,000 residents)',
    impactSummary: 'Record discharge from Hathnikund Barrage coupled with local monsoon rain pushed Yamuna to an all-time record water level.',
    keyDrivers: [
      'Upstream barrage peak release synchronization',
      'Severe riverbed siltation and choked regulatory flood gates'
    ],
    lessonsLearned: [
      'Continuous desiltation of drains and automated regulator gate control'
    ],
    badgeColor: 'bg-blue-600',
    dataPoint: {
      id: 'delhi-2023',
      locationName: 'Delhi NCR (Yamuna Basin - 2023 Deluge)',
      latitude: 28.6692,
      longitude: 77.2315,
      rainfall: 153,
      temperature: 31,
      humidity: 89,
      riverDischarge: 26500,
      waterLevel: 20.8,
      elevation: 214,
      landCover: 'Urban River Corridor',
      soilType: 'Alluvial Silt',
      populationDensity: 29000,
      infrastructureScore: 6,
      historicalFloods: 11,
      isDisasterBenchmark: true,
      disasterEventId: 'disaster-delhi-2023'
    }
  }
];

export const INITIAL_DATA: FloodDataPoint[] = [
  {
    id: '1',
    locationName: 'Guwahati, Assam',
    latitude: 26.1445,
    longitude: 91.7362,
    rainfall: 280,
    temperature: 28,
    humidity: 86,
    riverDischarge: 14500,
    waterLevel: 12.8,
    elevation: 55,
    landCover: 'Wetland / Alluvial Plain',
    soilType: 'Alluvial',
    populationDensity: 1200,
    infrastructureScore: 5,
    historicalFloods: 18
  },
  {
    id: '2',
    locationName: 'Patna, Bihar',
    latitude: 25.5941,
    longitude: 85.1376,
    rainfall: 220,
    temperature: 31,
    humidity: 78,
    riverDischarge: 18200,
    waterLevel: 10.4,
    elevation: 53,
    landCover: 'Agriculture / Basin',
    soilType: 'Silt',
    populationDensity: 1800,
    infrastructureScore: 4,
    historicalFloods: 22
  },
  {
    id: '3',
    locationName: 'Mumbai, Maharashtra',
    latitude: 19.0760,
    longitude: 72.8777,
    rainfall: 310,
    temperature: 29,
    humidity: 91,
    riverDischarge: 3400,
    waterLevel: 4.8,
    elevation: 10,
    landCover: 'Urban Coastal',
    soilType: 'Loam',
    populationDensity: 21000,
    infrastructureScore: 7,
    historicalFloods: 14
  },
  {
    id: '4',
    locationName: 'Delhi NCR',
    latitude: 28.6692,
    longitude: 77.2315,
    rainfall: 110,
    temperature: 32,
    humidity: 74,
    riverDischarge: 9200,
    waterLevel: 6.2,
    elevation: 214,
    landCover: 'Urban Floodplain',
    soilType: 'Alluvial Silt',
    populationDensity: 29000,
    infrastructureScore: 6,
    historicalFloods: 11
  },
  {
    id: '5',
    locationName: 'Kochi, Kerala',
    latitude: 9.9312,
    longitude: 76.2673,
    rainfall: 260,
    temperature: 28,
    humidity: 85,
    riverDischarge: 4600,
    waterLevel: 3.9,
    elevation: 2,
    landCover: 'Wetland',
    soilType: 'Clay',
    populationDensity: 1100,
    infrastructureScore: 6,
    historicalFloods: 10
  },
  {
    id: '6',
    locationName: 'Kolkata, West Bengal',
    latitude: 22.5726,
    longitude: 88.3639,
    rainfall: 240,
    temperature: 31,
    humidity: 84,
    riverDischarge: 9800,
    waterLevel: 7.6,
    elevation: 9,
    landCover: 'Deltaic Plain',
    soilType: 'Clayey Silt',
    populationDensity: 24000,
    infrastructureScore: 6,
    historicalFloods: 16
  },
  {
    id: '7',
    locationName: 'Srinagar, Jammu & Kashmir',
    latitude: 34.0837,
    longitude: 74.7973,
    rainfall: 95,
    temperature: 16,
    humidity: 62,
    riverDischarge: 5800,
    waterLevel: 6.1,
    elevation: 1585,
    landCover: 'Intermontane Valley',
    soilType: 'Rocky Loam',
    populationDensity: 900,
    infrastructureScore: 5,
    historicalFloods: 6
  },
  {
    id: '8',
    locationName: 'Jodhpur, Rajasthan',
    latitude: 26.2389,
    longitude: 73.0243,
    rainfall: 40,
    temperature: 41,
    humidity: 22,
    riverDischarge: 150,
    waterLevel: 0.9,
    elevation: 231,
    landCover: 'Arid / Semi-Arid',
    soilType: 'Sandy',
    populationDensity: 450,
    infrastructureScore: 5,
    historicalFloods: 1
  }
];

export const FEATURE_WEIGHTS = {
  rainfall: 0.30,
  waterLevel: 0.20,
  riverDischarge: 0.18,
  elevation: -0.14,
  historicalFloods: 0.10,
  populationDensity: 0.05,
  infrastructureScore: -0.05,
  humidity: 0.02
};
